### ISSUE TITLE
This module 'Az.Accounts' may override the existing commands

### ISSUE THREAD

**Issue by cblomart** [SureStacks/AzureAssess#4]
**Your Question**
Perhaps not an issue but more a question.
How do i deal with below error message. Not sure i want to override an existing module with an older one.

**Additional Context**
Install-Package: The following commands are already available on this system: 'Login-AzAccount,Logout-AzAccount,Resolve-Error,Send-Feedback'
The module 'Az.Accounts' may override the existing commands. If you still want to install this module 'Az.Accounts', use -AllowClobber parameter.

**Comment by martijnvanschie** [comment]
Check my issue #3 which is the same :)

I'm not a PowerShell guru but I fixed it by removing `AzureRM` and installing Az Module which is for PS7.
