### ISSUE TITLE
Using `Get-AzureAssessResources -ManagementGroupNames` on a Management Group with only child MG's fails

### ISSUE THREAD

**Issue by martijnvanschie** [SureStacks/AzureAssess#6]
**Describe the Bug**
When i run the command `Get-AzureAssessResources -ManagementGroupNames <NAME>` on a management group that contains no subscriptions, or only contains child management groups (due to governance structure) the script fails to run.

It seems to try to iterate an empty list.

**To Reproduce**
1. Run `Get-AzureAssessResources` on management groups without subscriptions.

**Expected Behavior**
It should not fail but handle the empty list and continue.
Best would be to iterate the sub management groups.

**Screenshots**

![image](https://github.com/SureStacks/AzureAssess/assets/8370550/9357092b-32eb-4ac3-af8a-fee7be359db1)

![image](https://github.com/SureStacks/AzureAssess/assets/8370550/3019e494-cf6c-4ae4-bca7-005183414f20)

**Environment (please complete the following information):**
 - OS: [e.g. Windows 11]
 - PowerShell version [e.g. 7.4]
 - Module Version [e.g. 0.1.23]

**Additional Context**

**Comment by cblomart** [comment]
The script doesn't handle managemenet group nesting (root management group). Currently the solution is to provide the list of the management groups containing subscriptions that you are intrested in. 
5e8635d
