### ISSUE TITLE
Power BI report fails on missing PublicIP in csv.

### ISSUE THREAD

**Issue by martijnvanschie** [SureStacks/AzureAssess#7]
**Describe the Bug**
When performing an import of a management group and then a subscription i get the error when opening the Power BI report.
The report is unable to parse the virtual machines file as there are no public IP's available in that file. 
There are virtual machines.

It seems to try to iterate an empty list.

**To Reproduce**
1. Import a management group and then a subscription

**Expected Behavior**
I would expect the Power BI report to open correctly and reflect the data model it should open.

**Screenshots**

![image](https://github.com/SureStacks/AzureAssess/assets/8370550/e553ab2a-d302-44e5-a303-297355dd53e2)

**Environment (please complete the following information):**
 - OS: [e.g. Windows 11]
 - PowerShell version [e.g. 7.4]
 - Module Version [e.g. 0.1.23]

**Additional Context**

**Comment by cblomart** [comment]
Hi, I updated the template. The new PowerBI template should solve this. [cc018a0](https://github.com/SureStacks/AzureAssess/commit/cc018a0e54911ae8aedde7c1ee1e1a5062d3eb13)

**Comment by cblomart** [comment]
I also had to update the code to correctly report public ip address.

**Comment by cblomart** [comment]
Should be updated with https://www.powershellgallery.com/packages/AzureAssess/0.1.24

**Comment by martijnvanschie** [comment]
I downloaded the latest Power BI template. Works now, even with the import i did with version 0.1.23.
Thank for the quick fix :)
