### ISSUE TITLE
Hardcoded path in Power BI templated prevents loading the report

### ISSUE THREAD

**Issue by martijnvanschie** [SureStacks/AzureAssess#8]
**Describe the Bug**
It looks like one of the files used for the report still has a hard coded path and does not work with the path input parameter asked when opening the template.

**To Reproduce**
1. Import a management group and then a subscription.
2. Open the template and fill in the path where the CLI was run.

**Expected Behavior**
I would expect the Power BI report to open correctly and reflect the data model it should open.

**Screenshots**

![image](https://github.com/SureStacks/AzureAssess/assets/8370550/fe7ee039-10a3-44d2-9c19-3f183ca3c3d9)

![image](https://github.com/SureStacks/AzureAssess/assets/8370550/7fd89279-6b04-42b5-98ef-f450b05c46d4)

**Environment (please complete the following information):**
 - OS: [e.g. Windows 11]
 - PowerShell version [e.g. 7.4]
 - Module Version [e.g. 0.1.23]

**Additional Context**

**Comment by cblomart** [comment]
Hi, I updated the template. The new PowerBI template should solve this. [cc018a0](https://github.com/SureStacks/AzureAssess/commit/cc018a0e54911ae8aedde7c1ee1e1a5062d3eb13)

**Comment by martijnvanschie** [comment]
Yep, seems to work now as intended.
